<a href="https://colab.research.google.com/github/JungYeoni/study_PerfectGuide_Python_MachineLearning/blob/main/2%EC%9E%A5/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 인코딩

## 레이블 인코딩 (Label Encoding)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [19]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder 객체 생성 후, fit(), transform()으로 label 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)

labels = encoder.transform(items) # 라벨 -> 숫자
print('인코딩 변환값', labels)

인코딩 변환값 [0 1 4 5 3 3 2 2]


In [20]:
# fit 과 transform을 한번에 써도 됨
labels = encoder.fit_transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


In [21]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [22]:
# 원본 값 출력
print('디코딩 원본 값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


## 원-핫 인코딩 (One-hot Encoding)

In [9]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [14]:
oh_labels

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (8, 6)>

In [12]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 2차원 ndarray로 변환
items = np.array(items).reshape(-1, 1)

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder 로 변환한 결과는 Sparse 행렬(희소 행렬)이므로 이를 Dense 행렬로 변환
print('원-핫 인코딩 데이터:')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원:')
print(oh_labels.shape)

원-핫 인코딩 데이터:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원:
(8, 6)


- pandas get_dummies 사용해서 원-핫 인코딩 하기


In [23]:
import pandas as pd

In [27]:
df = pd.DataFrame({'items': ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   items   8 non-null      object
dtypes: object(1)
memory usage: 196.0+ bytes


In [26]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0      True      False     False      False       False      False
1     False       True     False      False       False      False
2     False      False     False      False        True      False
3     False      False     False      False       False       True
4     False      False     False       True       False      False
5     False      False     False       True       False      False
6     False      False      True      False       False      False
7     False      False      True      False       False      False

# 피처 스케일링과 정규화
- 표준화: 평균이 0이고 분산이 1인 가우시안 정규분포를 가진 값으로 변환하는 것
- 정규화: 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념

사이킷런 피처 스케일링 지원
- `StandardScaler`: 평균이 0이고, 분산이 1인 정규분포 형태로 변환
- `MinMaxScaler`: 데이터값을 0과 1사이의 범위 값으로 변환 (음수 값이 있으면 -1에서 1값으로 변환)

- 회귀의 경우, 스케일링을 해준다고 성능이 무조건 좋아지는 것은 아니지만 성능이 좋아질 가능성이 있음

- Tree 계열은 스케일링의 영향을 받지 않음

## StandardScaler

In [28]:
from sklearn.datasets import load_iris
import pandas as pd

In [29]:
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값:')
print(iris_df.mean())
print('\nfeature 들의 분산 값:')
print(iris_df.var())

feature 들의 평균 값:
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값:
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [30]:
from sklearn.preprocessing import StandardScaler

In [32]:
# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터셋 변환
# scaler.fit(iris_df)
# iris_scaled = scaler.transform(iris_df)
scaler.fit_transform(iris_df)

# transform() 시 변환된 데이터셋이 numpy ndarray로 변환되기 때문에 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값:')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값:')
print(iris_df_scaled.var())

feature 들의 평균 값:
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값:
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


## MinMaxScaler

In [33]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler 로 데이터셋 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 변환된 데이터셋이 numpy ndarray로 변환되기 때문에 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 최소값:')
print(iris_df_scaled.min())
print('\nfeature 들의 최대값:')
print(iris_df_scaled.max())

feature 들의 최소값:
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature 들의 최대값:
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


## Scaler를 이용하여 학습 데이터와 테스트 데이터에 `fit()`, `fit_transform()` 적용 시 유의사항
-  scaler 는 2차원 이상의 데이터에 대해서만 가능함

In [39]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [40]:
# 학습 데이터는 0 부터 10까지. 테스트 데이터는 0 부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1. 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

In [43]:
# 확인
train_array, test_array, train_array.shape, test_array.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]),
 (11, 1),
 (6, 1))

In [41]:
# 최소값 0, 최대값 1로 변환하는 MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# fit() 하게 되면 train_array 데이터의 최소값이 0, 최대값 10으로 설정
scaler.fit(train_array)

# 1/10 scale로 train_array 데이터 변환함. 원본 10 -> 1로 변환됨
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [44]:
# fit() 하게 되면 train_array 데이터의 최소값이 0, 최대값 5으로 설정
scaler.fit(test_array)

# 1/10 scale로 train_array 데이터 변환함. 원본 5 -> 1로 변환됨
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test|_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test|_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


- train 에서는 5가 0.5인데 test 에서는 5가 1  
--> 척도가 맞지 않음

- **test에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform() 만으로 변환해야함**\
- 원래는 같이 묶어서 변환하기도하지만 test 데이터를 공개하고 싶지 않다면, 위와 같은 방법으로 진행해야함

In [45]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

test_scaled = scaler.transform(test_array)
print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test|_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test|_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
