<a href="https://colab.research.google.com/github/JungYeoni/study_PerfectGuide-master_python/blob/main/1%EC%9E%A5_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import zipfile

zip_file_path = '/content/drive/MyDrive/파이썬 머신러닝 완벽가이드/PerfectGuide-master.zip'
extraction_path = '/content/drive/MyDrive/파이썬 머신러닝 완벽가이드'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

print(f"'{zip_file_path}' 파일이 '{extraction_path}'에 성공적으로 압축 해제되었습니다.")

'/content/drive/MyDrive/파이썬 머신러닝 완벽가이드/PerfectGuide-master.zip' 파일이 '/content/drive/MyDrive/파이썬 머신러닝 완벽가이드'에 성공적으로 압축 해제되었습니다.


In [4]:
import numpy as np

In [5]:
# np.array() 사용법 알아보기
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
# 각 array의 차원 알아보기
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [7]:
# ndarray 내의 데이터 타입 확인
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [8]:
# 다른 데이터 유형이 섞여있는 리스트를 ndrray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용
list2 = [1,2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # int형이 유니코드 문자열 값으로 변환

list3 = [1,2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [9]:
# ndarray 내 데이터값의 변경
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기
* arange
* zeros: shape은 알지만 값은 모를 때
* ones

In [10]:
# arange() - 0부터 함수 인자값 -1까지의 값을 순차적으로 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [11]:
# zeros
zero_array = np.zeros((3, 2), dtype='int32') # 함수 인자로 튜플 형태의 shape값 입력
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2)) # dtype 안정해주면 default로 float64
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# reshape() - ndarray의 차원과 크기를 변경

In [12]:
array1 = np.arange(10)
print('array1: \n', array1)

array2 = array1.reshape(2, 5)
print('array2: \n', array2)

array3 = array2.reshape(5, 2)
print('array3: \n', array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
# 지정된 사이즈로 변경이 불가능하면 오류
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [14]:
# 인자로 -1을 적용하는 경우
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5) # 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환해라
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1) # 고정된 5개의 로우에 맞는 컬럼을 자동으로 새롭게 생성해 변환해라
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [15]:
# -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없음
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
# reshape(-1,1) - ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장
# -1: 알아서 맞춰라 / 1: 칼럼은 반드시 1개
# 3차원 -> 2차원, 1차원 -> 2차원
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist()) # tolist를 통해 리스트 자료형으로 변환 가능

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [17]:
# 3d -> 1d
array1d = array3d.reshape(-1, )
print(array1d)

[0 1 2 3 4 5 6 7]


# 인덱싱(indexing) - ndarray의 데이터 세트 선택하기

* 단일 값 추출

In [18]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2] # 세번째 데이터값을 의미
print('value:', value) # 단일 인덱싱을 하게되면 차원을 하나 줄여줌
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [19]:
print('맨 뒤에 값:', array1[-1], '맨 뒤에서 두 번째 값: ', array1[-2])

맨 뒤에 값: 9 맨 뒤에서 두 번째 값:  8


In [20]:
# 값 바꾸기
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [21]:
# 2d array에서 확인
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index가 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index가 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index가 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index가 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index가 가리키는 값: 1
(row=0, col=1) index가 가리키는 값: 2
(row=1, col=0) index가 가리키는 값: 4
(row=2, col=2) index가 가리키는 값: 9


* 2d라 편의를 위해 row, col로 지칭
* 정확한 표현은 axis 0 axis 1이 맞는 표현임.

* 슬라이싱

In [22]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
array3 = array1[0:3]
print('array3:', array3)
print(type(array3)) # 슬라이싱이기 때문에 여전히 type이 ndarray -> 차원이 줄지 않음.

array1: [1 2 3 4 5 6 7 8 9]
array3: [1 2 3]
<class 'numpy.ndarray'>


In [23]:
array3.shape

(3,)

In [24]:
array1 = np.arange(start=1, stop=10)

# 위치 인덱스 0-2(2포함)까지 추출
array4 = array1[0:3]
print(array4)

# 위치 인덱스 3부터 마지막까지 추출
array5 = array1[3:]
print(array5)

# 위치 인덱스로 전체 데이터 추출
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [25]:
# 2d
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)
print('\n')
print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('\n')
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('\n')
print('array2d[1:3, :]\n', array2d[1:3, :])
print('\n')
print('array2d[:,:]\n', array2d[:,:])
print('\n')
print('array2d[:2, 1:]\n', array2d[:2, :1])
print('\n')
print("array2d[:2, 0]\n", array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array2d[0:2, 0:2]
 [[1 2]
 [4 5]]


array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]


array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]


array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array2d[:2, 1:]
 [[1]
 [4]]


array2d[:2, 0]
 [1 4]


In [26]:
# 2차원에 대해서 단일 인덱싱 -> 1차원 (row 위치 인덱스)
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


- 팬시 인덱싱: 불연속적인 값을 가져올 수 있음

In [27]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d, '\n')

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


- 불린 인덱싱

<동작방식>
1. boolean 조건을 []내에 입력
2. False 값은 무시하고 True 값에 해당하는 index만 지정
3. 저장된 index 값으로 데이터 조회

코드적으로는 조건만 쓰면 ndarray 데이터셋을 반환하기 때문에 로직에 신경안쓰고 쉽게 코딩이 가능함.

In [28]:
array1d = np.arange(start=1, stop=10)
print(array1d)
# [ ] 안에 불린 인덱싱 적용
array3 = array1d[array1d > 5]
print('array1d > 5 boolean indexing 결과 값:', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 boolean indexing 결과 값: [6 7 8 9]


In [29]:
# 조건문만 수행했을 때
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [30]:
val = array1d > 5
print(val, type(val), val.shape) # type으로 ndarray가 나옴

[False False False False False  True  True  True  True] <class 'numpy.ndarray'> (9,)


In [31]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3) # True인 위치 인덱스만 출력

불린 인덱스로 필터링 결과: [6 7 8 9]


In [32]:
array1d = np.arange(start=1, stop=10)
target = []
# 불린 인덱싱을 적용하지 않았을 경우
for i in range(0, 9):
  if array1d[i] > 5:
    target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [33]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print("일반 인덱스로 필터링 결과:", array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


# 행렬의 정렬

`np.sort()` : 넘파이에서 sort()를 호출하는 방식  -> 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 형태 반환   
`ndarray.sort()`: 행렬 자체에서 sort()를 호출하는 방식 -> 원 행렬 자체를 정렬한 형태로 반환, 반환값은 None

In [37]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 배열:', sort_array2)
print('org_array.sort() 호출 후 반환된 배열:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
org_array.sort() 호출 후 반환된 배열: None
org_array.sort() 호출 후 반환된 배열: [1 3 5 9]


In [39]:
# 내림차순으로 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [43]:
# 2d
array2d = np.array([[8, 12],
                     [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬 행렬의 인덱스 반환

In [44]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [46]:
# 내림차순
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 배열의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 배열의 인덱스: [2 3 0 1]


In [47]:
# argsort()로 하는 키매핑 *넘파이는 메타 데이터를 가질 수 없음

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# score순으로 이름을 알고싶을
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array 의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) # 팬시 인덱싱

성적 오름차순 정렬 시 score_array 의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산

In [48]:
# 행렬 내적
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 19],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  82]
 [139 199]]


In [49]:
# 전치 행렬
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]
